#
# Makefile for the Mstar MSG2xxx touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_FT6X36_TS) += focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FT6X36_EX_FUN) += focaltech_ex_fun.o
obj-$(CONFIG_TOUCHSCREEN_FT6X36_CTL) += focaltech_ctl.o