fpc1020-objs := fpc1020_main.o fpc1020_common.o fpc1020_input.o fpc1020_capture.o fpc1020_regulator.o
# called from kernel build system: just declare what our modules are
obj-$(CONFIG_FPC1020) := fpc1020.o


